version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-10-container
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8082:80"
    networks:
      - laravelnetwork
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8082
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3307
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    networks:
      - laravelnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    networks:
      - laravelnetwork

networks:
  laravelnetwork:
    driver: bridge
